{{- if .Values.cronjob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "ml-vision-chart.fullname" . }}-cronjob
  namespace: ingress-nginx
  labels:
    {{- include "ml-vision-chart.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "ml-vision-chart.selectorLabels" . | nindent 12 }}
        spec:
          restartPolicy: OnFailure
          nodeSelector:
            kakaoi.io/kke-nodepool: team2-ml-vision
          containers:
          - name: {{ .Release.Name }}-cronjob
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: Always
            command: ["python", "quiz/cronjob_quiz_generator.py"]  # 크론잡 실행 스크립트
            env:
            - name: PROFILE
              value: "{{ .Values.profile }}"
            envFrom:
            - configMapRef:
                name: {{ .Values.configMapName }}
            - secretRef:
                name: db-secret
            - secretRef:
                name: s3-secret
            - secretRef:
                name: proxy-secret
            {{- if .Values.autoscaling.enabled }}
            resources:
              requests:
                memory: {{ .Values.cronjob.memoryRequest | default "2Gi" }}
                cpu: {{ .Values.cronjob.cpuRequest | default "500m" }}
                {{- if gt (.Values.autoscaling.gpuRequest | int) 0 }}
                nvidia.com/gpu: {{ .Values.autoscaling.gpuRequest }}
                {{- end }}
              limits:
                memory: {{ .Values.cronjob.memoryLimit | default "4Gi" }}
                cpu: {{ .Values.cronjob.cpuLimit | default "1000m" }}
                {{- if gt (.Values.autoscaling.gpuLimit | int) 0 }}
                nvidia.com/gpu: {{ .Values.autoscaling.gpuLimit }}
                {{- end }}
            {{- end }}
          imagePullSecrets:
          - name: kc-cr-secret
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
{{- end }}
