{{- if .Values.autoscaling.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ml-vision-chart.fullname" . }}-deployment
  namespace: ingress-nginx
  labels:
    {{- include "ml-vision-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.deployment.maxUnavailable }}
      maxSurge: {{ .Values.deployment.maxSurge }}
  selector:
    matchLabels:
      {{- include "ml-vision-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ml-vision-chart.selectorLabels" . | nindent 8 }}
      annotations:
        configmap-checksum: {{ include (print $.Template.BasePath "/ml-vision-config.yaml") . | sha256sum }}
    spec:
      nodeSelector:
        kakaoi.io/kke-nodepool: team2-ml-vision
      containers:
      - name: {{ .Release.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        env:
        - name: PROFILE
          value: "{{ .Values.profile }}"
        envFrom:
        - configMapRef:
            name: {{ .Values.configMapName }}
        - secretRef:
            name: s3-secret
        - secretRef:
            name: proxy-secret
        - secretRef:
            name: db-secret
        ports:
        - containerPort: 8080
        {{- if .Values.autoscaling.enabled }}
        resources:
          requests:
            memory: {{ .Values.autoscaling.memoryRequest }}
            cpu: {{ .Values.autoscaling.cpuRequest }}
            {{- if gt (.Values.autoscaling.gpuRequest | int) 0 }}
            nvidia.com/gpu: {{ .Values.autoscaling.gpuRequest }}
            {{- end }}
          limits:
            memory: {{ .Values.autoscaling.memoryLimit }}
            cpu: {{ .Values.autoscaling.cpuLimit }}
            {{- if gt (.Values.autoscaling.gpuLimit | int) 0 }}
            nvidia.com/gpu: {{ .Values.autoscaling.gpuLimit }}
            {{- end }}
        {{- end }}
      imagePullSecrets:
      - name: kc-cr-secret
{{- end }}