apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "front-chart.fullname" . }}-deployment
  namespace: ingress-nginx
  labels:
    {{- include "front-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.deployment.maxUnavailable }}
      maxSurge: {{ .Values.deployment.maxSurge }}
  selector:
    matchLabels:
      {{- include "front-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "front-chart.selectorLabels" . | nindent 8 }}
      annotations:
        configmap-checksum: {{ include (print $.Template.BasePath "/front-config.yaml") . | sha256sum }}
    spec:
      nodeSelector:
        kakaoi.io/kke-nodepool: team2-front
      containers:
      - name: {{ .Release.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        env:
        - name: PROFILE
          value: "{{ .Values.profile }}"
        envFrom:
        - configMapRef:
            name: {{ .Values.configMapName }}
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        {{- if .Values.autoscaling.enabled }}
        resources:
          requests:
            memory: {{ .Values.autoscaling.memoryRequest }}
            cpu: {{ .Values.autoscaling.cpuRequest }}
          limits:
            memory: {{ .Values.autoscaling.memoryLimit }}
            cpu: {{ .Values.autoscaling.cpuLimit }}
        {{- end }}
      imagePullSecrets:
      - name: kc-cr-secret