# 이름 오버라이드 설정
fullnameOverride: "api"

image:
  repository: {{ .Values.apiImageRepository | default "scratcha-backend" }}
  tag: "20250824054606-f1412e709bec19dc13d7ffaf901bb6e9aeb0d0f2"
deployment:
  maxUnavailable: 0
  maxSurge: 1
service:
  type: ClusterIP
  port: 80
  targetPort: 8001
configMapName: app-config
profile: "local"

# HPA 설정
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
  #메모리 제한 설정
  memoryLimit: "1Gi"
  memoryRequest: "500m"
  cpuLimit: "1000m"
  cpuRequest: "500m"