apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: front-app
  namespace: argocd
  annotations:
    # 짧은 폴링 간격 설정 (30초)
    argocd.argoproj.io/refresh: "30s"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jihun-01/test.git
    targetRevision: HEAD
    path: helm-chart/front-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
