name: Deploy to ArgoCD

on:
  push:
    branches: [ main ]
    paths:
      - 'helm-chart/front-chart/**'
      - 'helm-chart/api-chart/**'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.12.0
        
    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        
    - name: Package Front Helm chart
      run: |
        cd helm-chart/front-chart
        helm package .
        echo "Front chart packaged successfully"
        
    - name: Package API Helm chart
      run: |
        cd helm-chart/api-chart
        helm package .
        echo "API chart packaged successfully"
        
    - name: Validate Front Helm chart
      run: |
        cd helm-chart/front-chart
        helm lint .
        echo "Front chart validation passed"
        
    - name: Validate API Helm chart
      run: |
        cd helm-chart/api-chart
        helm lint .
        echo "API chart validation passed"
        
    - name: Notify ArgoCD deployment
      run: |
        echo "Helm chart source code has been updated"
        echo "ArgoCD will automatically detect the change and deploy the new version"
        echo "No need to push chart package - ArgoCD reads from source directly"
        
    - name: Notify deployment
      run: |
        echo "Deployment triggered for Helm chart source code changes"
        echo "Check ArgoCD dashboard for deployment status"
        echo "ArgoCD will automatically sync when it detects changes in the helm-chart directory"
