name: Deploy to ArgoCD

on:
  push:
    branches: [ main ]
    paths:
      - 'helm-chart/front-chart/**'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:

env:
  HELM_CHART_NAME: front-chart
  HELM_CHART_VERSION: "0.1.0"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.12.0
        
    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        
    - name: Package Helm chart
      run: |
        cd helm-chart/front-chart
        helm package .
        echo "Helm chart packaged successfully"
        
    - name: Validate Helm chart
      run: |
        cd helm-chart/front-chart
        helm lint .
        echo "Helm chart validation passed"
        
    - name: Notify ArgoCD deployment
      run: |
        echo "Helm chart source code has been updated"
        echo "ArgoCD will automatically detect the change and deploy the new version"
        echo "No need to push chart package - ArgoCD reads from source directly"
        echo "ArgoCD Server: ${{ env.ARGOCD_SERVER }}"
        echo "ArgoCD Namespace: ${{ env.ARGOCD_NAMESPACE }}"
        
    - name: Notify deployment
      run: |
        echo "Deployment triggered for Helm chart source code changes"
        echo "Check ArgoCD dashboard for deployment status"
        echo "ArgoCD will automatically sync when it detects changes in the helm-chart directory"
